#!/usr/bin/env sh

set -eu

if git diff --cached --quiet --exit-code; then
  exit 0
fi

STAGED_FILES=$(git diff --cached --name-only --diff-filter=d)

make format

echo "$STAGED_FILES" | xargs git add
